import "@radix-ui/themes/styles.css";
import bootstrap from "bootstrap/dist/css/bootstrap.min.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import { Theme } from "@radix-ui/themes";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";
import prisma from "@/prisma/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SECRET = new TextEncoder().encode(process.env.SESSION_SECRET);

export default async function RootLayout({ children }) {
  const sessionCookie = (await cookies().get("session"))?.value;
  let isLoggedIn = false;
  let isPremium = false;

  if (sessionCookie) {
    try {
      const { payload } = await jwtVerify(sessionCookie, SECRET);
      if (payload?.userId) {
        const user = await prisma.user.findUnique({
          where: { id: payload.userId },
        });
        if (user) {
          isLoggedIn = true;
          isPremium = !!user.isPremium;
        }
      }
    } catch {}
  }

  return (
    <html lang="en">
      <body>
        <Theme>
          {isLoggedIn && <NavBar isPremium={isPremium} />}
          {children}
        </Theme>
      </body>
    </html>
  );
}
